spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    name: startkit
    url: jdbc:mysql://mysql:3306/startkit
    username: root
  jpa:
    hibernate:
      ddl-auto: none
  redis:
    database: 1
    host: redis
    port: 6379

server:
  port: 8081

some_service:
  name: some
  url: http://some-service.com:8080
